import { deepseekAdvisorRunGate } from '../advisor/deepseek_run_gate.js';

export const PHASE_SHIFT_WORKSTREAMS = Object.freeze([
  {
    id: 'deepseek_dry_run_calibration',
    priority: 1,
    status: 'active',
    objective: 'Expand recorded-snapshot advisor calibration before real API calls.',
    achievementCriteria: Object.freeze([
      'first-call request pack, capture template, and replay harness stay generated by deterministic eval',
      'saved model responses, when captured later, pass strict replay before any live advisor trust',
      'advisor prompt size, JSON validity, skill validity, activation acceptance, rejection behavior, and calibration-tier coverage are reported without API calls by default',
    ]),
  },
  {
    id: 'deepseek_gated_live_calibration',
    priority: 2,
    status: 'queued',
    objective: 'Allow DeepSeek proposals only through the validated skill-boundary queue path on a private server.',
    achievementCriteria: Object.freeze([
      'MCBOT_ALLOW_DEEPSEEK=1 and private live-test gates are required before any real advisor call',
      'DeepSeek proposals are accepted only through schema validation and activation-guarded queue staging',
      'live calibration logs prove accepted, rejected, stale, unsafe, and recovery proposals without bypassing reactive survival',
    ]),
  },
  {
    id: 'benchmark_ladder',
    priority: 3,
    status: 'queued',
    objective: 'Track repeatable offline and live tasks for gather/deposit, fishing, mining, building, PvM, death recovery, and return-on-time missions.',
    achievementCriteria: Object.freeze([
      'each benchmark declares setup, command, expected result, evidence artifact, and live/offline status',
      'benchmark reports separate live-proven behavior from offline-covered behavior',
      'failures create targeted blockers instead of reopening broad substrate hardening',
    ]),
  },
  {
    id: 'long_horizon_missions',
    priority: 4,
    status: 'queued',
    objective: 'Turn timed fishing/mining and route/deposit/return loops into durable reusable mission controllers.',
    achievementCriteria: Object.freeze([
      'timed missions plan return-by time before the deadline rather than starting return at the deadline',
      'mission loops handle deposit, food/tool state, hazards, interruptions, and clean stop/resume decisions',
      'multi-hour behavior is validated through scaled offline tests and bounded private-server soaks',
    ]),
  },
  {
    id: 'combat_ladder',
    priority: 5,
    status: 'queued',
    objective: 'Advance private-server PvM first, then authorized PvP mechanics through ordinary game actions and plausible timing.',
    achievementCriteria: Object.freeze([
      'PvM engage/flee decisions are proven across escalating private-server hostile fixtures',
      'player combat remains disabled unless explicitly authorized and gated to private/local contexts',
      'advanced tactics use normal game actions and exclude kill-aura, aimbot, packet spoofing, and public-server behavior',
    ]),
  },
  {
    id: 'viewer_operator_track',
    priority: 6,
    status: 'queued',
    objective: 'Provide persistent human oversight and document later handoff paths without relying on rendered pixels for planning state.',
    achievementCriteria: Object.freeze([
      'viewer is read-only oversight and can remain open across bot reconnects',
      'handoff path is documented as viewer-first, normal logout/relogin for Regime B Phase 1, and Fabric bridge later',
      'DeepSeek continues to consume structured world-model snapshots instead of rendered pixels',
    ]),
  },
  {
    id: 'publication_track',
    priority: 7,
    status: 'queued',
    objective: 'Keep demo scripts, evidence logs, benchmark tables, and capability matrices current for external review.',
    achievementCriteria: Object.freeze([
      'status, progress, deterministic eval, and benchmark artifacts are enough for an external reviewer to reproduce claims',
      'capability claims name the exact evidence level: live-proven, offline-covered, scaffolded, or pending',
      'resume-facing material emphasizes authorized private-server autonomy and avoids public-server cheating claims',
    ]),
  },
]);

export const PHASE_SHIFT_TRANSITION = Object.freeze({
  readyStatus: 'phase_shift_ready',
  blockedStatus: 'deterministic_gate_closure',
  stopBroadPolishingRule: 'When F1 and F2 evidence are both satisfied, stop broad deterministic substrate polishing and move into F3 calibration plus the SOTA-track workstreams.',
  nextGoalObjective: 'Regenerate calibration from real F1/F2 response evidence, then advance the SOTA-track workstreams while deterministic validators still own activation.',
  allowedPostGateDeterministicWork: Object.freeze([
    'direct benchmark blockers',
    'deterministic skill-boundary fixes discovered by DeepSeek dry-run/live calibration',
    'safety regressions',
    'publication evidence gaps',
  ]),
});

export function evaluatePhaseShiftReadiness(inputs = {}) {
  const defaultDeepSeekGate = deepseekAdvisorRunGate({}, { entrypoint: 'phase-shift' });
  const firstLiveCall = inputs.firstLiveCall || null;
  const firstLivePlan = inputs.firstLivePlan || null;
  const advisorDryRun = inputs.advisorDryRun || null;
  const liveEvidence = inputs.liveEvidence || {};
  const docs = inputs.docs || {};
  const f1Satisfied = firstLiveCallOk(firstLiveCall);
  const f2Satisfied = firstLivePlanOk(firstLivePlan);

  const gates = [
    gate({
      id: 'deepseek_default_off',
      label: 'DeepSeek off by default',
      satisfied: defaultDeepSeekGate.ok === false
        && defaultDeepSeekGate.reasons.includes('MCBOT_ALLOW_DEEPSEEK=1 required to allow DeepSeek advisor calls'),
      evidence: 'deepseekAdvisorRunGate({}) refuses without MCBOT_ALLOW_DEEPSEEK=1 and makes no API call.',
      blocker: 'DeepSeek entrypoints must fail closed without explicit opt-in.',
    }),
    gate({
      id: 'f1_first_live_call',
      label: 'F1 first live frontier-model call',
      satisfied: f1Satisfied,
      status: f1Satisfied ? 'live-proven' : 'pending',
      evidence: firstLiveCallEvidence(firstLiveCall),
      blocker: 'Run one explicitly gated DeepSeek frontier-model call through npm run advisor:first-call, store the private raw capture, and verify strict replay plus response metrics.',
    }),
    gate({
      id: 'f2_first_live_plan',
      label: 'F2 first live private-server plan',
      satisfied: f2Satisfied,
      status: f2Satisfied ? 'live-proven' : 'pending',
      evidence: firstLivePlanEvidence(firstLivePlan),
      blocker: 'Run the Regime A private-LAN "gather 10 oak logs" live plan with DeepSeek enabled, prove planner/schema/activation/executor/final outcome/cost guard, and survive one induced hostile flee.',
    }),
  ];

  const strictGates = [
    gate({
      id: 'advisor_queue_boundary',
      label: 'Advisor queue proposals are activation-validated',
      satisfied: inputs.queueProposalBoundary === true,
      evidence: inputs.queueProposalBoundaryEvidence
        || 'stageAdvisorQueueReplacement validates fresh snapshots before executor queue replacement.',
      blocker: 'Queue proposal staging evidence is missing.',
    }),
    gate({
      id: 'advisor_dry_run_benchmark',
      label: 'Advisor dry-run benchmark is clean',
      satisfied: advisorDryRunOk(advisorDryRun),
      evidence: advisorDryRunEvidence(advisorDryRun),
      blocker: 'Run npm run advisor:dry-run and clear unexpected outcomes plus prompt budget violations.',
    }),
    liveGate({
      id: 'j_hostile_escalation',
      label: 'J hostile escalation fixture',
      evidence: liveEvidence.hostileEscalation,
      defaultBlocker: 'Needs live proof or an exact documented block reason for MCBOT_LIVE_HOSTILE_ESCALATION_FIXTURE_OK, MCBOT_LIVE_ADMIN_OK, and MCBOT_RCON_PASSWORD.',
    }),
    liveGate({
      id: 'k_pvm_escalation',
      label: 'K PvM escalation decision fixture',
      evidence: liveEvidence.pvmEscalation,
      defaultBlocker: 'Needs live proof or an exact documented block reason for MCBOT_LIVE_PVM_ESCALATION_FIXTURE_OK, MCBOT_LIVE_ADMIN_OK, and MCBOT_RCON_PASSWORD.',
    }),
    gate({
      id: 'deterministic_baseline',
      label: 'Deterministic baseline passes',
      satisfied: inputs.deterministicBaselinePassed === true,
      evidence: inputs.deterministicBaselineEvidence || 'check, unit, grep, and deterministic eval commands pass.',
      blocker: 'Run npm run test:all and clear failures.',
    }),
    gate({
      id: 'status_docs_current',
      label: 'Status docs name phase-shift risks',
      satisfied: docs.statusNamesPhaseShift === true && docs.goalNamesPhaseShift === true,
      evidence: 'docs/status.md and docs/goal.det-autonomy-v1.md contain phase-shift tracking.',
      blocker: 'Update docs/status.md and docs/goal.det-autonomy-v1.md with current phase-shift risks and commands.',
    }),
  ];

  const ready = gates.every((entry) => entry.satisfied);
  const blockers = gates
    .filter((entry) => !entry.satisfied)
    .map((entry) => ({ id: entry.id, label: entry.label, reason: entry.blocker }));
  const strictReady = strictGates.every((entry) => entry.satisfied);
  const strictBlockers = strictGates
    .filter((entry) => !entry.satisfied)
    .map((entry) => ({ id: entry.id, label: entry.label, reason: entry.blocker }));
  const apiCallMade = inputs.deepSeekApiCallMade === true
    || firstLiveCallMadeApiCall(firstLiveCall)
    || firstLivePlanMadeApiCall(firstLivePlan);

  return {
    ready,
    currentPhase: ready ? 'sota_track' : 'deterministic_gate_closure',
    noDeepSeekApiCall: !apiCallMade,
    gates,
    blockers,
    strictReadiness: {
      ready: strictReady,
      gates: strictGates,
      blockers: strictBlockers,
      note: 'Optional strict readiness is reported for auditability but does not block the F1+F2 phase-shift gate.',
    },
    workstreams: PHASE_SHIFT_WORKSTREAMS,
    transition: buildTransition({ ready, blockers }),
    nextWorkstream: ready
      ? PHASE_SHIFT_WORKSTREAMS[0]
      : null,
  };
}

export function renderPhaseShiftReadiness(report) {
  const lines = [
    '# Phase Shift Readiness',
    '',
    `- current phase: ${report.currentPhase}`,
    `- ready for SOTA track: ${report.ready ? 'yes' : 'no'}`,
    `- no DeepSeek API call made: ${report.noDeepSeekApiCall === true ? 'yes' : report.noDeepSeekApiCall === false ? 'no' : 'unknown'}`,
    '',
    '## Gates',
    '',
    '| Gate | Status | Evidence / blocker |',
    '| --- | --- | --- |',
  ];

  for (const gateResult of report.gates || []) {
    const status = gateResult.satisfied ? gateResult.status : 'pending';
    const detail = gateResult.satisfied ? gateResult.evidence : gateResult.blocker;
    lines.push(`| ${gateResult.label} | ${status} | ${escapeTable(detail)} |`);
  }

  const strict = report.strictReadiness || null;
  if (strict) {
    lines.push(
      '',
      '## Optional Strict Readiness',
      '',
      `- ready: ${strict.ready ? 'yes' : 'no'}`,
      `- note: ${strict.note || 'strict readiness does not block the F1+F2 phase-shift gate'}`,
      '',
      '| Gate | Status | Evidence / blocker |',
      '| --- | --- | --- |',
    );
    for (const gateResult of strict.gates || []) {
      const status = gateResult.satisfied ? gateResult.status : 'pending';
      const detail = gateResult.satisfied ? gateResult.evidence : gateResult.blocker;
      lines.push(`| ${gateResult.label} | ${status} | ${escapeTable(detail)} |`);
    }
  }

  lines.push('', '## Workstreams', '');
  for (const workstream of report.workstreams || []) {
    lines.push(`- ${workstream.priority}. ${workstream.id}: ${workstream.status} - ${workstream.objective}`);
    for (const criterion of workstream.achievementCriteria || []) {
      lines.push(`  - done when: ${criterion}`);
    }
  }

  if (report.transition) {
    lines.push('', '## Transition Rule', '');
    lines.push(`- status: ${report.transition.status}`);
    lines.push(`- next action: ${report.transition.nextAction}`);
    lines.push(`- stop rule: ${report.transition.stopBroadPolishingRule}`);
    lines.push(`- next goal objective: ${report.transition.nextGoalObjective}`);
    lines.push(`- allowed post-gate deterministic work: ${report.transition.allowedPostGateDeterministicWork.join(', ')}`);
  }

  if (Array.isArray(report.blockers) && report.blockers.length > 0) {
    lines.push('', '## Blockers', '');
    for (const blocker of report.blockers) {
      lines.push(`- ${blocker.label}: ${blocker.reason}`);
    }
  }

  return `${lines.join('\n')}\n`;
}

function buildTransition({ ready, blockers }) {
  const firstBlocker = Array.isArray(blockers) && blockers.length > 0 ? blockers[0] : null;
  return {
    status: ready ? PHASE_SHIFT_TRANSITION.readyStatus : PHASE_SHIFT_TRANSITION.blockedStatus,
    nextAction: ready
      ? PHASE_SHIFT_WORKSTREAMS[0].id
      : `clear gate: ${firstBlocker?.id || 'unknown'}`,
    stopBroadPolishingRule: PHASE_SHIFT_TRANSITION.stopBroadPolishingRule,
    nextGoalObjective: ready
      ? PHASE_SHIFT_TRANSITION.nextGoalObjective
      : 'Clear the named readiness blockers before moving the active goal into SOTA-track work.',
    allowedPostGateDeterministicWork: [...PHASE_SHIFT_TRANSITION.allowedPostGateDeterministicWork],
  };
}

function gate({ id, label, satisfied, evidence, blocker, status = 'passed' }) {
  return {
    id,
    label,
    satisfied: satisfied === true,
    status,
    evidence,
    blocker,
  };
}

function liveGate({ id, label, evidence, defaultBlocker }) {
  const normalized = evidence || {};
  const liveProven = normalized.liveProven === true;
  const documentedBlocked = normalized.documentedBlocked === true && Boolean(normalized.reason);
  return gate({
    id,
    label,
    satisfied: liveProven || documentedBlocked,
    status: liveProven ? 'live-proven' : 'documented-blocked',
    evidence: liveProven
      ? normalized.evidence || 'live fixture is proven'
      : normalized.reason || defaultBlocker,
    blocker: normalized.reason || defaultBlocker,
  });
}

function firstLiveCallOk(report) {
  if (!report || typeof report !== 'object') return false;
  const replay = report.responseReplay || report.replayValidation || null;
  if (firstLiveCallReplayOk(report, replay)) return true;

  const capture = report.capture || {};
  const responseCount = Number(capture.responseCount ?? report.responseCount);
  const responseSummaries = Array.isArray(capture.responseChars) ? capture.responseChars : [];
  const metricsReady = responseSummaries.length > 0
    ? responseSummaries.every((entry) => entry.metricsReady === true)
    : report.strictValidationPreview?.metricsReplayOk === true
      || report.responseMetricsReady === true
      || report.metricsReady === true;
  const replayOk = report.strictValidationPreview?.replayOk === true
    || report.validation?.ok === true
    || report.replay?.ok === true;

  return report.status === 'captured_first_call_responses'
    && report.noApiCall === false
    && Number(report.requestCount ?? responseCount) === 1
    && capture.wroteResponseFile === true
    && responseCount === 1
    && replayOk
    && metricsReady;
}

function firstLiveCallMadeApiCall(report) {
  return report?.noApiCall === false
    || report?.status === 'captured_first_call_responses'
    || report?.capture?.status === 'captured_first_call_responses'
    || firstLiveCallReplayOk(report, report?.responseReplay || report?.replayValidation);
}

function firstLiveCallEvidence(report) {
  if (!report) return 'F1 evidence is missing; reports/advisor-first-call.json has not captured a real response.';
  const replay = report.responseReplay || report.replayValidation || null;
  if (firstLiveCallReplayOk(report, replay)) {
    const metrics = replay.summary?.responseMetrics || {};
    const tokenUsage = metrics.tokenUsage || {};
    const latency = metrics.latencyMs || {};
    const result = Array.isArray(replay.results) ? replay.results[0] : null;
    return [
      `status=${replay.status || 'unknown'}`,
      'noApiCall=false',
      `requests=${replay.expectedCount ?? report.requestCount ?? 'unknown'}`,
      `responses=${replay.presentCount ?? 'unknown'}`,
      `privateCapture=${report.responseOutput?.nonEmptyResponseCount === 1 || replay.presentCount === 1}`,
      `replayOk=${replay.ok === true}`,
      `metricsReady=${replay.responseMetricsReadyCount === 1}`,
      `model=${result?.responseMetrics?.model || 'unknown'}`,
      `latencyMs=${latency.max ?? result?.responseMetrics?.latencyMs ?? 'unknown'}`,
      `totalTokens=${tokenUsage.totalTokens ?? result?.responseMetrics?.totalTokens ?? 'unknown'}`,
    ].join('; ');
  }

  const capture = report.capture || {};
  const preview = report.strictValidationPreview || {};
  const responseCount = Number(capture.responseCount ?? report.responseCount ?? 0);
  const metricSummary = Array.isArray(capture.responseChars)
    ? capture.responseChars.map((entry) => `${entry.id || 'response'}:${entry.metricsReady ? 'metrics-ready' : 'metrics-missing'}`).join(',')
    : `metricsReplayOk=${preview.metricsReplayOk === true}`;
  return [
    `status=${report.status || 'unknown'}`,
    `noApiCall=${report.noApiCall === true ? 'true' : report.noApiCall === false ? 'false' : 'unknown'}`,
    `requests=${report.requestCount ?? 'unknown'}`,
    `responses=${responseCount}`,
    `wrotePrivateFile=${capture.wroteResponseFile === true}`,
    `replayOk=${preview.replayOk === true || report.validation?.ok === true || report.replay?.ok === true}`,
    metricSummary,
  ].join('; ');
}

function firstLiveCallReplayOk(report, replay) {
  if (!report || !replay || typeof replay !== 'object') return false;
  const result = Array.isArray(replay.results) ? replay.results[0] : null;
  const hasPrivateCapture = report.responseOutput?.nonEmptyResponseCount === 1
    || replay.presentCount === 1;
  return replay.ok === true
    && replay.status === 'validated_model_responses'
    && Number(replay.expectedCount) === 1
    && Number(replay.presentCount) === 1
    && Number(replay.missingCount || 0) === 0
    && Number(replay.unknownCount || 0) === 0
    && Number(replay.duplicateCount || 0) === 0
    && Number(replay.unexpectedOutcomes || 0) === 0
    && Number(replay.promptBudgetViolations || 0) === 0
    && Number(replay.requestFingerprintReadyCount || 0) === 1
    && Number(replay.requestFingerprintMismatchCount || 0) === 0
    && Number(replay.responseMetricsReadyCount || 0) === 1
    && hasPrivateCapture
    && report.captureGuard?.ok === true
    && result?.expectationMet === true
    && result?.requestFingerprintStatus === 'matched'
    && result?.responseMetrics?.provider === 'deepseek'
    && Number.isFinite(result?.responseMetrics?.latencyMs)
    && Number.isFinite(result?.responseMetrics?.totalTokens);
}

function firstLivePlanOk(report) {
  if (!report || typeof report !== 'object') return false;
  const planner = report.planner || report.advisor || {};
  const activation = report.activation || {};
  const executor = report.executor || {};
  const finalOutcome = report.finalOutcome || report.outcome || {};
  const cost = report.cost || report.advisorCost || {};
  const costGuard = report.costCeilingGuard || report.costGuard || {};
  const hostileFlee = report.hostileFlee || report.inducedHostileFlee || {};
  const diagnostics = report.diagnostics || {};
  const ranSkillCount = Number(executor.ranSkillCount ?? executor.skillRunCount ?? report.executorSkillCount ?? 0);
  const acceptedSteps = Number(planner.acceptedSteps ?? planner.maxAcceptedSteps ?? 0);
  const failedSkillCount = Number(executor.failedSkillCount ?? 0);
  const failureCount = Array.isArray(diagnostics.failures) ? diagnostics.failures.length : 0;

  return report.ok === true
    && ['live_plan_completed', 'completed', 'success'].includes(String(report.status || ''))
    && isRegimeA(report)
    && planner.callMade === true
    && planner.schemaValid === true
    && acceptedSteps >= 1
    && activation.accepted === true
    && ranSkillCount >= 1
    && failedSkillCount === 0
    && failureCount === 0
    && finalOutcome.reported === true
    && Number.isFinite(cost.usd ?? cost.totalUsd ?? report.costUsd)
    && costValue(cost, report) >= 0
    && costGuard.verified === true
    && hostileFlee.survived === true;
}

function firstLivePlanMadeApiCall(report) {
  return report?.noApiCall === false
    || report?.planner?.callMade === true
    || report?.advisor?.callMade === true;
}

function firstLivePlanEvidence(report) {
  if (!report) return 'F2 evidence is missing; expected a private-server live-plan report for the Regime A gather-10-oak-logs run.';
  const planner = report.planner || report.advisor || {};
  const activation = report.activation || {};
  const executor = report.executor || {};
  const finalOutcome = report.finalOutcome || report.outcome || {};
  const cost = report.cost || report.advisorCost || {};
  const costGuard = report.costCeilingGuard || report.costGuard || {};
  const hostileFlee = report.hostileFlee || report.inducedHostileFlee || {};
  const diagnostics = report.diagnostics || {};
  const ranSkillCount = Number(executor.ranSkillCount ?? executor.skillRunCount ?? report.executorSkillCount ?? 0);
  const acceptedSteps = Number(planner.acceptedSteps ?? planner.maxAcceptedSteps ?? 0);
  const failedSkillCount = Number(executor.failedSkillCount ?? 0);
  const failureCount = Array.isArray(diagnostics.failures) ? diagnostics.failures.length : 0;
  return [
    `status=${report.status || 'unknown'}`,
    `ok=${report.ok === true}`,
    `regime=${report.accountRegime || report.regime || report.account?.regime || 'unknown'}`,
    `account=${report.account?.username || report.username || 'unknown'}`,
    `plannerCall=${planner.callMade === true}`,
    `schemaValid=${planner.schemaValid === true}`,
    `acceptedSteps=${acceptedSteps}`,
    `activationAccepted=${activation.accepted === true}`,
    `executorSkills=${ranSkillCount}`,
    `failedSkills=${failedSkillCount}`,
    `failures=${failureCount}`,
    `finalOutcomeReported=${finalOutcome.reported === true}`,
    `costUsd=${costValue(cost, report)}`,
    `costGuardVerified=${costGuard.verified === true}`,
    `inducedHostileFleeSurvived=${hostileFlee.survived === true}`,
  ].join('; ');
}

function isRegimeA(report) {
  const regime = String(report.accountRegime || report.regime || report.account?.regime || '').toLowerCase();
  const username = String(report.account?.username || report.username || '').toLowerCase();
  const auth = String(report.account?.auth || report.auth || '').toLowerCase();
  return (regime === 'test' || regime === 'regime_a' || regime === 'a')
    && (!username || username === 'mcbot')
    && (!auth || auth === 'offline');
}

function costValue(cost = {}, report = {}) {
  const value = cost.usd ?? cost.totalUsd ?? report.costUsd;
  return Number.isFinite(value) ? value : Number(value);
}

function advisorDryRunOk(report) {
  if (!report || report.ok !== true) return false;
  const summary = report.summary || {};
  if (typeof summary.coverageViolations === 'number') {
    return summary.coverageViolations === 0
      && summary.unexpectedOutcomes === 0
      && summary.promptBudgetViolations === 0;
  }
  const categories = summary.categoryCounts || {};
  return summary.unexpectedOutcomes === 0
    && summary.promptBudgetViolations === 0
    && categories.mission_plan >= 1
    && categories.combat_gate >= 1
    && categories.safety_gate >= 1
    && categories.staleness_gate >= 1;
}

function advisorDryRunEvidence(report) {
  if (!report) return 'advisor dry-run report is missing';
  const summary = report.summary || {};
  return [
    `${report.fixtureCount || 0} fixtures`,
    `unexpected=${summary.unexpectedOutcomes ?? 'unknown'}`,
    `promptBudgetViolations=${summary.promptBudgetViolations ?? 'unknown'}`,
    `coverageViolations=${summary.coverageViolations ?? 'unknown'}`,
    `firstCallReadiness=${report.firstCallReadiness?.status || 'unknown'}`,
    `categories=${Object.keys(summary.categoryCounts || {}).join(',') || 'none'}`,
    `calibrationTiers=${Object.keys(summary.calibrationTierCounts || {}).join(',') || 'none'}`,
  ].join('; ');
}

function escapeTable(value) {
  return String(value ?? '').replaceAll('|', '\\|');
}

export default {
  PHASE_SHIFT_WORKSTREAMS,
  PHASE_SHIFT_TRANSITION,
  evaluatePhaseShiftReadiness,
  renderPhaseShiftReadiness,
};
